[package]
name = "suspishous"
version = "127.0.0.1"
authors = ["Imposters and amongus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
